language: swift
os: osx
osx_image: xcode9.3
xcode_project: KipalogAPI.xcodeproj
xcode_sdk: iphonesimulator11.4
notifications:
  email: false

env:
  global:
    - FRAMEWORK_NAME=KipalogAPI

script:
    - xcodebuild -project KipalogAPI.xcodeproj -scheme KipalogAPI -configuration Test -sdk macosx CONFIGURATION_BUILD_DIR=. clean build

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME

