language: swift
os: osx
osx_image: xcode9.3

notifications:
  email: false

script:
    - xcodebuild -project KipalogAPI.xcodeproj -scheme KipalogAPI -configuration Test -sdk macosx CONFIGURATION_BUILD_DIR=. clean build

