language: swift
os: osx
osx_image: xcode9.3
notifications:
  email: false

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace KipalogAPI.xcworkspace -scheme KipalogAPITests CODE_SIGNING_REQUIRED=NO
